area-Assimp:
- any: ['src/Assimp/**/*']

area-BuildTools:
- any: ['src/Core/Silk.NET.BuildTools/**/*']

area-Input:
- any: ['src/Input/**/*']

area-Windowing:
- any: ['src/Windowing/**/*']

area-OpenAL:
- any: ['src/OpenAL/**/*']

area-OpenCL:
- any: ['src/OpenCL/**/*']

area-OpenGL:
- any: ['src/OpenGL/**/*']

area-OpenXR:
- any: ['src/OpenXR/**/*']

area-Vulkan:
- any: ['src/Vulkan/**/*']

area-DirectX/Windows:
- any: ['src/Microsoft/**/*']

area-Metal:
- any: ['src/Apple/Metal/**/*']

area-FEMFX:
- any: ['src/AMD/FEMFX/**/*']

platform-GLFW:
- any: ['src/Windowing/Silk.NET.GLFW/**/*',
        'src/Windowing/Silk.NET.Windowing.Desktop/**/*',
        'src/Windowing/Silk.NET.Windowing.Glfw/**/*']
