name: 'Continuous Deployment'
pr: none

trigger:
- 'refs/tags/v*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Release
  condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')
  pool:
    vmImage: 'windows-latest'

  variables:
    buildConfiguration: 'Release'
    dotnetCoreVersion: '3.1.100'

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.1'
    inputs:
      version: $(dotnetCoreVersion)
  - script: dotnet run --configuration $(buildConfiguration) --project src/Core/BuildTools/BuildTools.csproj build/binder_scripts/build.json
    displayName: 'Bind'
  - script: dotnet pack --configuration $(buildConfiguration)
    displayName: 'Build/Pack'
  - script: dotnet nuget push build/output_packages/Silk.NET*.nupkg -s https://api.nuget.org/v3/index.json -k $(NUGET_API_KEY) -n true
    displayName: 'Push to NuGet'
  - publish: build/output_packages
    artifact: NuGet Packages
